name: cv
description: A new Flutter application.

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fluro: ^1.3.7

  async: ^2.0.8
  rxdart: ^0.19.0

  http : ^0.12.0
  json_annotation: ^2.0.0
  shared_preferences: ^0.4.3

  intl: ^0.15.7
  intl_translation: ^0.17.0

  material_design_icons_flutter: ^2.7.94

  transparent_image: ^0.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/account_card_details-white.png
   - images/account_card_details-blue.png
   - images/default-avatar.png
   - images/default-banner.jpg

  fonts:
       - family: Google Sans
         fonts:
           - asset: fonts/GoogleSans-Regular.ttf
           - asset: fonts/GoogleSans-Medium.ttf
             weight: 500
           - asset: fonts/GoogleSans-Bold.ttf
             weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
