name: social_cv_client_flutter
description: A new Flutter application.

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:

  # Common Social CV Logic
  social_cv_client_dart_common:
    git: https://github.com/axellebot/Social-CV-Client-Dart-common
    version: ^1.0.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logging: ^0.11.3+2

  fluro: ^1.3.7

  async: ^2.0.8
  rxdart: ^0.20.0

  # HTTP Client
  http: ^0.12.0
  dio: ^1.0.13

  shared_preferences: ^0.4.3

  # Translations
  intl: ^0.15.7
  intl_translation: ^0.17.0

  transparent_image: ^0.1.0

  # Icons
  material_design_icons_flutter: ^2.7.94
  #cupertino_icons: ^0.1.0

dev_dependencies:
  build_runner: ^1.0.0

  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/account_card_details-white.png
  - assets/images/account_card_details-blue.png
  - assets/images/default-avatar.png
  - assets/images/default-banner.jpg

  - secrets.json # secret data


  fonts:
  - family: Google Sans
    fonts:
    - asset: assets/fonts/GoogleSans-Regular.ttf
    - asset: assets/fonts/GoogleSans-Medium.ttf
      weight: 500
    - asset: assets/fonts/GoogleSans-Bold.ttf
      weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

authors:
- Axel LE BOT <axellebot@gmail.com>