name: social_cv_client_flutter
description: A new Flutter application.

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:

  # Common Social CV Logic
  social_cv_client_dart_common:
    path: ../Social-CV-Client-Dart-common
  #    git:
  #      url: https://github.com/axellebot/Social-CV-Client-Dart-common
  #      ref: develop

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Routes
  fluro: ^1.3.7

  # Async/Rx
  async: ^2.0.8
  rxdart: ^0.22.0

  # Bloc Pattern
  flutter_bloc: ^0.13.0

  # Dependency Injection
  provider: ^2.0.1

  # Storage
  shared_preferences: ^0.4.3

  # Serialization
  json_annotation: ^2.3.0

  # Translations
  intl: ^0.15.7
  intl_translation: ^0.17.0

  # UI Widgets
  transparent_image: ^0.1.0

  # Icons
  material_design_icons_flutter: ^2.7.94
  #cupertino_icons: ^0.1.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.3.0

  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/account_card_details-white.png
    - assets/images/account_card_details-blue.png
    - assets/images/default-avatar.png
    - assets/images/default-banner.jpg

    - config.json # secret data


  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

authors:
  - Axel LE BOT <axellebot@gmail.com>